<?php
$dfd=Mage::getStoreConfig('Gimmie');

$enablegimmie= $dfd['messages']['enablegimmi'];

$consumerkey= $dfd['messages']['consumerkey'];

$sectetkey= $dfd['messages']['secretkey'];


$country= $dfd['messages']['country'];

$locale= $dfd['messages']['locale'];

$help=$dfd['messages']['help'];

$style=$dfd['messages']['style'];


$responsivewidgetyesno=$dfd['messages']['responsivewidgetyesno'];
if($responsivewidgetyesno==1)
{
  $responsivewidgetyesno='false';

}   
else
{

  $responsivewidgetyesno='true';
}    



$rewardtabyesno=$dfd['messages']['rewardtabyesno'];

if($rewardtabyesno==1)
{
  $rewardtabyesno='false';

}   
else
{

  $rewardtabyesno='true';
}



$profiletabyesno=$dfd['messages']['profiletabyesno'];
if($profiletabyesno==1)
{
  $profiletabyesno='false';

}   
else
{

  $profiletabyesno='true';
} 



$profileredemptionyesno=$dfd['messages']['profileredemptionyesno'];
if($profileredemptionyesno==1)
{
  $profileredemptionyesno='true';

}   
else
{

  $profileredemptionyesno='false';
}



$profileactivitiesyesno=$dfd['messages']['profileactivitiesyesno'];
if($profileactivitiesyesno==1)
{
  $profileactivitiesyesno='true';

}   
else
{

  $profileactivitiesyesno='false';
}


$leaderboardyesno=$dfd['messages']['leaderboardyesno'];
if($leaderboardyesno==1)
{
  $leaderboardyesno='false';

}   
else
{

  $leaderboardyesno='true';
}


$leaderboardmostpointsyesno=$dfd['messages']['leaderboardmostpointsyesno'];
if($leaderboardmostpointsyesno==1)
{
  $leaderboardmostpointsyesno='true';

}   
else
{

  $leaderboardmostpointsyesno='false';
}


$leaderboardmostrewardsyesno=$dfd['messages']['leaderboardmostrewardsyesno'];
if($leaderboardmostrewardsyesno==1)
{
  $leaderboardmostrewardsyesno='true';

}   
else
{

  $leaderboardmostrewardsyesno='false';
}


$leaderboardmostvalueyesno=$dfd['messages']['leaderboardmostvalueyesno'];
if($leaderboardmostvalueyesno==1)
{
  $leaderboardmostvalueyesno='true';

}   
else
{

  $leaderboardmostvalueyesno='false';
}
$customer = Mage::getSingleton('customer/session')->getCustomer();


$firstname = $customer->getFirstname();
$lastname = $customer->getLastname();
$email = $customer->getEmail();

?>



<ul class="links"<?php if($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif;?>>

<?php
if($enablegimmie=="1" && $customer->getId())
{
?>

<li class="first"><a href="#" gm-view="catalog">Rewards (Current Points: <span class="gimmie-user-points">...</span>)</a></li>


<?php 

}
?>


</ul>




       <div id="gimmie-root"></div>
<script type="text/javascript">
var _gimmie = {
  "endpoint"                    : "http://www.gimmieworld.com/demo/gimmie-test/gimmie-connect.php?player=<?php echo $email; ?>&key=<?php echo $consumerkey; ?>&secret=<?php echo $sectetkey; ?>&logout=true&&gimmieapi=",
    "gimmie_endpoint"             : "http://api.gimmieworld.com", // An optional endpoint for bypassing secret authentication
    "key"                         : "<?php echo $consumerkey; ?>",
    "country"                     : "<?php echo $country; ?>",
    "locale"                      : "<?php echo $locale; ?>",
    "user"                        : {
      "name"                      : "<?php echo $firstname; ?> <?php echo $lastname; ?>",
        "realname"                  : "<?php echo $firstname; ?> <?php echo $lastname ; ?>",
        "email"                     : "<?php echo $email; ?>",
        "avatar"                    : ""
                          },    "options"                     : {
                            "animate"                   : true,
                              "auto_show_notification"    : true,
                              "notification_timeout"      : 8,
                              "responsive"                : <?php echo $responsivewidgetyesno; ?>,
                              "show_anonymous_rewards"    :  <?php echo $rewardtabyesno; ?>,
                              "shuffle_reward"            : true,
                              "default_level_icon"        : "",
                              "pages"                     : {
                                "catalog"                 : {
                                  "hide"                  : false
                              },
                              "profile"                 : {
                                "hide"                  :<?php echo $profiletabyesno; ?>,
                                  "redemptions"           :<?php echo $profileredemptionyesno; ?>,
                                  "mayorships"            : true,
                                  "badges"                : true,
                                  "activities"            :<?php echo $profileactivitiesyesno; ?>
                              },
                              "leaderboard"             : {
                                "table"                 : "alltime", //alltime,thisweek,last7days,pastweek,today,last30days,pastmonth,thismonth
                                  "hide"                  :<?php echo $leaderboardyesno; ?>,
                                  "mostpoints"            :<?php echo $leaderboardmostpointsyesno; ?>,
                                  "mostrewards"           :<?php echo $leaderboardmostrewardsyesno; ?>,
                                  "mostvalues"            :<?php echo $profileactivitiesyesno; ?>
                              }
                            }
                          },
                            "events"                      : {
                              "widgetLoad"                : function () {
                                console.log ('Loaded');
                            },
                              "login"                     : function () {
                                console.log ('Login');
                            },
                              "loadLeaderboard"           : function (data, cb) {
                                //data
                                cb(data);
                            }
                          },
                            "text"                        : {
                              "help"                      : "<?php echo $help; ?>"
                          },
                          "templates"                   : {
                          }

                        };
                        (function(d){
                          var js, id = "gimmie-widget", ref = d.getElementsByTagName("script")[0];
                          if (d.getElementById(id)) {return;}
                          js = d.createElement("script"); js.id = id; js.async = true;
                          js.src = "//api.gimmieworld.com/cdn/gimmie-widget2.all.js";
                          ref.parentNode.insertBefore(js, ref);
                        }(document));
                      </script>

       <style>
            <?php echo $style;?>
            </style>
