<?php
  $country = Mage::getStoreConfig('Gimmie/general/country');
  if ($country == 'auto') {
    $ip = Mage::helper('core/http')->getRemoteAddr();
    $country = trim(file_get_contents('http://api.wipmania.com/'.$ip));
  }

  $session = Mage::getSingleton('customer/session');
  if ($session->isLoggedIn()) {
    $customer = $session->getCustomer()->getData();
    $name = htmlspecialchars($customer['firstname'].' '.$customer['lastname']);
    $email = $customer['email'];
  }
?>
<style>
  .gimmie-dashboard a {
    text-decoration: none;
  }
  
  .gimmie-dashboard .content-link img {
    vertical-align: middle;
    width: 28px;
    margin-left: 10px;
  }

  <?php echo Mage::getStoreConfig('Gimmie/text_and_styles/widget_style'); ?>
</style>
<script type="text/javascript">
  window._gimmie = {
      
	    "endpoint"                    : "<?php echo Mage::getUrl('gimmie/index/proxy'); ?>?target=",
	    "key"                         : "<?php echo Mage::getStoreConfig('Gimmie/general/consumer_key'); ?>",
	    "country"                     : "<?php echo $country; ?>", 
	    <?php if ($session->isLoggedIn()) { ?>
	    
	    "user"                        : {
	        "external_uid"              : "<?php echo $email; ?>",
	        // Display name
	        "name"                      : "<?php echo $name; ?>",
	        // Gateway name
	        "realname"                  : "<?php echo $name; ?>",
	        "email"                     : "<?php echo $email; ?>"
	    },
	    
	    <?php } ?>
	    
	    "options"                     : {
	      "animate"                   : true,
	      "auto_show_notification"    : true,
	      "notification_timeout"      : <?php echo Mage::getStoreConfig('Gimmie/views/notification_timeout'); ?>,
	      "responsive"                : true,
	      "show_anonymous_rewards"    : true,
	      "shuffle_reward"            : true,
	      "pages"                       : {
          "catalog"                   : {
            "hide_sponsor_here"       : <?php echo (Mage::getStoreConfig('Gimmie/views/hide_sponsor_here') == 0 ? 'false' : 'true'); ?>,
	          "hide"                    : <?php echo (Mage::getStoreConfig('Gimmie/views/catalog_view') == 0 ? 'true' : 'false'); ?>
	        },
	        "profile"                   : {
	          "hide"                    : <?php echo (Mage::getStoreConfig('Gimmie/views/profile_view') == 0 ? 'true' : 'false'); ?>
	          
	        },
	        "leaderboard"               : {
	          "hide"                    : <?php echo (Mage::getStoreConfig('Gimmie/views/leaderboard_view') == 0 ? 'true' : 'false'); ?>
	          
	        }
	      }	      
	    },
	    "text"                        : {
	      "help"                      : "<?php echo Mage::getStoreConfig('Gimmie/text_and_styles/widget_help'); ?>",
	      "help_url"                  : "<?php echo Mage::getStoreConfig('Gimmie/text_and_styles/widget_help_url'); ?>",
<?php echo Mage::getStoreConfig('Gimmie/text_and_styles/widget_text'); ?>
	    },
	    "templates"                   : {}
  };

  window.onload = function () {
    var gimmieRoot = document.createElement('div');
    gimmieRoot.id = 'gimmie-root';
    document.body.appendChild(gimmieRoot);
    
    (function(d){
      var js, id = "gimmie-widget", ref = d.getElementsByTagName("script")[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement("script"); js.id = id; js.async = true;
      js.src = "https://api.gimmieworld.com/assets/gimmie-widget2.all.js";
      ref.parentNode.insertBefore(js, ref);
    }(document));  
  }
</script>
