<script type="text/javascript">
  window._gimmie = {

  };

  (function () {
    var gimmieRoot = document.createElement('div');
    gimmieRoot.id = 'gimmie-root';
    document.body.appendChild(gimmieRoot);
    
    (function(d){
      var js, id = "gimmie-widget", ref = d.getElementsByTagName("script")[0];
      if (d.getElementById(id)) {return;}
      js = d.createElement("script"); js.id = id; js.async = true;
      js.src = "http://api.llun.in/assets/gimmie-widget2.all.js";
      ref.parentNode.insertBefore(js, ref);
    }(document));  
  })();
</script>